### ISSUE TITLE
Press 4 ntsc pinn boot rca not working! black screen no matter what do

### ISSUE THREAD

**Issue by ghost** [procount/pinn#110]
This is an bug that noobs does also haves! the only bootloader that works without issue here is berryboot.

Would like to see the problem fixed on pinn!

Raspberry pi3 model b hardware working ok!

Pressing 4 while it loads makes no difference. still black screen on rca output! as far as pinn is my favorite OS installer i do want to see it working as fast as possible to be able to use it again =( i do really miss it!

Thanks

**Comment by procount** [comment]
PINN uses the same codebase as NOOBS for this feature. I hope they will have time to fix it so that I can incorporate it into PINN too.
Option 4 executes the following code to select NTSC output:
`tvservice -o; tvservice -c 'NTSC 4:3'`
I do not have access to an NTSC TV as I am in the UK, so I cannot test it.
Please provide the NOOBS team (on your NOOBS issue) with appropriate information to help them identify the problem.
If you have a Raspbian system that works fine with NTSC mode on the RCA output, then please provide the output of `tvservice -s` and the content of your `/boot/config.txt` file.

**Comment by procount** [comment]
No answer
