### ISSUE TITLE
Lakka Installation Error

### ISSUE THREAD

**Issue by hahagu** [procount/pinn#137]
Attempting to install Lakka with PINN or NOOBS gives the following error.

```
Error downloading or extracting tarball
xz: (stdin): Compressed data is corrupt
Cannot write to '-' (No such file or directory).
./SYSTEM: Truncated tar archive
bsdtar: Error exit delayed from previous errors.
```

I am using a Samsung EVO 64gb (SDXC) microSD, formatted FAT32 with gparted utility.
I also tried using a 16gb microSD card to make sure that it wasn't the card's fault.

The other distros, such as Raspbian, and LibreElec installs flawlessly.

**Comment by procount** [comment]
Which model of Pi are you using?
Which version of PINN are you using?

I have just tried installing Lakka2 on my pi 3B+ using v2.5.1 of PINN that I just released, and it installed without problem, although I don't think Lakka has been upgraded to use the new LAN and wifi of the 3B+ yet.

**Comment by hahagu** [comment]
I am using RPi3
and is using the latest PINN version from sourceforge, from the date I posted.
I will try again with the latest version and repost.

**Comment by hahagu** [comment]
Hi, I just tried it with the latest version, 252a, and it still outputs the same error.
I am using the same board, with the same hardware.

**Comment by procount** [comment]
Ok. I'll check the same combination. It could be you just have to wait til lakka is upgraded. Or just use an older version of pinn like 2.4.5f from the archive folder.

**Comment by procount** [comment]
I have just installed Lakka_rpi2 with PINN v2.5.2a on a Pi3. PINN auto-upgraded the firmware and it installed from the internet and booted fine.

**Comment by hahagu** [comment]
Hmm.. That's weird..
I wonder what's wrong..
Because it doesn't seem like I'm doing anything wrong..
btw, if it matters, I used gparted on ubuntu live to format the 64gb microSD and 16gb microSD as FAT32

**Comment by procount** [comment]
I'm sure you haven't done anything wrong. ( I think I tried it again and I got a kernel panic :-/ )
There are some strange incompatibilities going on at the moment, due to the enforced firmware upgrade.
Please bear with me whilst they are sorted out.
Although your particular problem looks more like an interrupted download rather than "a failure to boot" problem.

If you want to try something....... 
Please download pinn-245f.zip from my archive folder on sourceforge.
Backup the bootcode.bin and recovery.elf files on your PINN 2.5.2a installed SD card.
Extract the 2 files: bootcode.bin and recovery.elf from pinn-245f.zip and replace the files on your PINN 2.5.2a SD card with these ones.
Try installing Lakka again.

If that fails with the same xz/bsdtar error again, replace all PINN files on your SD card with the files from pinn-245f.zip and try again.

Let me know how you get on.

**Comment by hahagu** [comment]
Unfortunately, both of your proposed solutions did not work for me.
Note that I did not reformat the microSD cards.
Also, this happens in the latest version of NOOBS as well.

**Comment by procount** [comment]
How did they fail?

**Comment by hahagu** [comment]
The same exact error.

**Comment by procount** [comment]
So re-reading this thread, I think I assumed your problem was related to the recent problems with upgrading the firmware for the new 3B+ which seems to have had other consequences, although I hinted at an interrupted download problem. I think this is your real problem - for some reason your download is not working properly for Lakka.

To avoid other firmware problems, I suggest you use PINN_245f since you are using the RPI3.

I suggest you try downloading Lakka manually to a USB stick, insert the stick into your RPi and install it from there instead of directly from the internet. That way you have more control and can be sure the downloads have been done properly. Check each file size to make sure they are complete.

1. Go to http://mirror.lakka.tv/noobs/Lakka_RPi2/ and download all of the files and folders that you see at that location. 
2. Create a folder on your USB stick called /os/Lakka_RPi2 and copy this structure into the folder.
3. Insert your USB stick into your Pi and boot PINN. You do not need to be connected to the internet to install from USB.

(You could choose the "Download" option from within PINN, but as you _seem_ to be having trouble with this particular download, it may have the same problem)

**Comment by hahagu** [comment]
This is weird, because I used the USB, and it gives
**`Error downloading or extracting tarball
xz: (stdin): Compressed data is corrupt
./SYSTEM: Truncated tar archive
bsdtar: Error exit delayed from previous errors.`**
Hmm... Maybe the Lakka tar itself is bad?

Edit: I just tried extracting Lakka_RPi2_System.tar.xz from 7zip, and it gives a data error.
Looks like the archive was bad all along...

Edit2: So I downloaded a nightly, which tar was not corrupt from 
http://sources.lakka.tv/nightly/RPi2.arm/?C=M&O=D
and it did extract in 7zip. However, the same error appeared.
Now I really am out of ideas :P
Maybe my board is bad? But that shouldn't really affect the software portion...
