### ISSUE TITLE
Build Failure on Ubuntu 17

### ISSUE THREAD

**Issue by dlabun** [procount/pinn#139]
While rebuilding PINN I am getting the following error that's causing the build to fail. I don't see this error if I rebuild NOOBS. The only change I made to the code was adjusting config.txt with my display settings.

`rm gcc.pod`
`make[3]: Leaving directory '/home/douglas/pinn-master/buildroot/output/build/host-gcc-final-4.8.4/build/gcc`
`Makefile:3909: recipe for target 'all-gcc' failed`
`make[2]: *** [all-gcc] Error 2`
`make[2]: Leaving directory '/home/douglas/pinn-master/buildroot/output/build/host-gcc-final-4.8.4/build'`
`Makefile:857: recipe for target 'all' failed`
`make[1]: *** [all] Error 2`
`make[1]: Leaving directory '/home/douglas/pinn-master/buildroot/output/build/host-gcc-final-4.8.4/build'`
`package/pkg-generic.mk:182: recipe for target '/home/douglas/pinn-master/buildroot/output/build/host-gcc-final-4.8.4/.stamp_built' failed`
`make: *** [/home/douglas/pinn-master/buildroot/output/build/host-gcc-final-4.8.4/.stamp_built] Error 2`

**Comment by procount** [comment]
I've not seen that error before with gcc.
Are you building everything from scratch in a clean folder?
I did a lot of tidying up in 2.4.5g to ensure everything built cleanly and all dependencies were correct from a fresh `git clone`, so that should build ok.
Try a `make clean` first and try again.

What distro are you building in?
I'm using Ubuntu 14.04.
If you're using a later version (with GCC 6), I think there is a gcc patch that should be applied. See the NOOBS issues for it. https://github.com/raspberrypi/noobs/issues/427

https://github.com/XECDesign/noobs/commit/ec219c64bd59ec5d88fdc3e5ec78636498563604

**Comment by dlabun** [comment]
I have Ubuntu 16 LTS (I think, not a Linux user...). I'll grab that patch see how it goes.

**Comment by dlabun** [comment]
With the patch it failed in the same spot... I'm going to grab a copy of Ubuntu 14.04 and see if I can build successfully on it.

**Comment by dlabun** [comment]
Everything works fine when building on Ubuntu 14.0.4 LTS... I updated the title of this issue since I had actually downloaded Ubuntu 17 originally and it seems to be isolated to something with 17 and the patch not fixing it.
