### ISSUE TITLE
RetroPI

### ISSUE THREAD

**Issue by OxygenGS** [procount/pinn#144]
How do i install retroPI with pinn?

**Comment by procount** [comment]
Did you just post this question on the forum, too?

Which RPi model do you have?
The current version 4.3 of Retropie does not yet support the RPi3B+.
There is a test version that apparently does, but I need to convert it to the NOOBS/PINN format first.

**Comment by OxygenGS** [comment]
RPi3B+. Ok cool! When would that be?

**Comment by procount** [comment]
Did you just post this question on the forum as hoenens? (no point in me answering the same question twice :wink: )

The rpi3B+ has limited OSes at the moment due to it being so new - maintainers have to update all their OSes to suit.

I have tried to download the test Retropie, but it failed twice with network errors. 
I'll get it done asap, but I'm very busy at the moment, so please bear with me.

**Comment by OxygenGS** [comment]
Cool ty so much!

**Comment by procount** [comment]
4.3.15 for 3B+ is now available as retropie3
