### ISSUE TITLE
kali linux kernel panic

### ISSUE THREAD

**Issue by pctechadam** [procount/pinn#149]
Fresh install of kali linux from pinn on pi 3b fails to boot with a kernel panic error. On this SD card are three other working operating systems. I checked the cmdline.txt and it has the correct partition for the root file system.

**Comment by procount** [comment]
3b or 3b+?

**Comment by pctechadam** [comment]
No + just the 3b

**Comment by procount** [comment]
My 3B is busy at the moment, but I tried installing Kali2 on a 2B from the internet and it booted fine to the login prompt. 
You could try re-installing just Kali to see if that helps. Otherwise I'll try and install it on a 3B when I get a changce to see if there are any problems with it, but it certainly looks ok on the 2B.

**Comment by pctechadam** [comment]
I got the chance to test single install seems to work without issues.

**Comment by procount** [comment]
What do you mean by a 'single install'?

- Using PINN to install just Kali2 on its own?
- Installing Kali2 as a normal image without using PINN?
- Using PINN to re-install Kali2

I hope to get my Pi3B back soon so I can test this.

**Comment by procount** [comment]
Since the version of Kali that PINN installs predates the 3B+, it will only work with PINN when PINN has the old firmware installed. Did you try to boot it when the firmware button on the archival menu said "3B+" in red? If so, just click the button to downgrade PINN's firmware indicated by the button saying "0123" in blue, then try booting it again.

**Comment by pctechadam** [comment]
Thank you. I had forgotten that i clicked on that. It works without any
issues thank for your help.

**Comment by procount** [comment]
Cool!

This transitionary period is quite complicated....
