### ISSUE TITLE
Autoupdate Auto Update Option?

### ISSUE THREAD

**Issue by MartinX3** [procount/pinn#220]
Dear developers,

I'm sorry, if I didn't found this function, but is it possible to let PINN automatically update itself, if it finds an update?
I don't want everytime to grab my remote and point to the accept button, if there is a new update.
It should just immediately update.

**Comment by procount** [comment]
No. Not at the moment.
There is an option for it to NOT check for updates but it is necessary to accept the update manually.
But it looks like a nice feature so I will look to add it for those who like to live at the bleeding edge!

**Comment by MartinX3** [comment]
Aren't there different update channels to avoid bleeding edge?
Which versions should I avoid?
I just install every update which comes. 
Except the "can't update itself anymore" bug, it just worked at my site.
(It's only starting libreelec and raspian is installed, but not used)

**Comment by procount** [comment]
There is only the 1 update channel.
You should always update to the latest version to make sure you have the latest features and (hopefully not so many) bugfixes.
But for some users it's just a question of _when_ it is convenient to update. For others they might want to wait until it has matured before updating. It's personal preference. But this option will provide more choice so I like it. I think I may call it "forceupdate".

**Comment by procount** [comment]
> Except the "can't update itself anymore" bug,

Can you remind me what this is please?

**Comment by MartinX3** [comment]
@procount you fixed it last year or earlier.
We needed to install the new update manually, because the updater did not mention any update anymore.

**Comment by procount** [comment]
Oh ok. If I have fixed it that's fine. i thought it was still outstanding :wink:

**Comment by lurch** [comment]
> I think I may call it "forceupdate"

Perhaps "forcepinnupdate" (or similar) to make it clear that it only force-updates PINN and doesn't update any of the OSes?

**Comment by procount** [comment]
Forceupdatepinn ?
Iirc the option to update the OSes is "silentreinstallnewer" so it is already quite different, but I suppose in isolation it's maybe not so clear.

**Comment by MartinX3** [comment]
@procount
Won't upgrade libreelec or raspian itself?
Will I need to reinstall them? Data loss?

**Comment by procount** [comment]
@MartinX3 - please stay away from `silentreinstallnewer` :smile:

Once you have installed LibreElec or Raspbian, you can upgrade them using the standard apt-get type tools. You do not need PINN to update them. PINN only restores to a factory fresh version of the OS, (or restores a backup if you have made one).

`silentreinstallnewer` WILL cause data loss, because it will replace the OSes named in the `select` option with the latest factory fresh version of that OS, thus wiping out any modifications you have made or data you have stored indiscriminantly!

I hope I have put enough warnings about this in its description in the documentation:
https://github.com/procount/pinn/blob/master/README_PINN.md#auto-reinstalling-oses

It is for a very specific use case where the OS needs to be updated regularly and it doesn't contain any data. In this case the data would normally be stored in a separate data partition. It doesn't apply to any of the OSes that PINN provides. It would be for a more dedicated OS that is able to automatically find and mount its data partition. Of course there are other ways to do such a thing (e.g. docker or resin-io {balena now?}) but this is a very simplistic way to do it with PINN.

**Comment by lurch** [comment]
> (e.g. docker or resin-io {balena now?})

Yeah, I believe resin-io is now balenaCloud.

**Comment by procount** [comment]
forceupdatepinn is now implemented in p3.0.4.

**Comment by MartinX3** [comment]
Thank you!
