### ISSUE TITLE
fatCP437: Invalid argument 

### ISSUE THREAD

**Issue by YenLegion** [procount/pinn#222]
I am getting this line when performing a filesystem check upon first installing PINN. I am using a brand new so card. I ran a full format in the official SD format application. I wiped the card once with a quick format then ran chkdsk but still am having the same error. What might be causing this? Here is an image of the disk check results. 

https://imgur.com/gallery/XZcUE16

Thank you.

**Comment by procount** [comment]
I haven't seen that error before and I only found 1 google entry about it which wasn't very helpful.
It seems to happen before the file check. Maybe it is to do with code pages?
What size SD card are you using?
Have you changed the language and/or keyboard layout used in PINN?
In any case, it doesn't seem to cause a problem because the fsck completes without errors. So I wouldn't worry too much.
I will look into the code to see it I can spot anything but it might be difficult to debug if I cannot replicate it.

**Comment by lurch** [comment]
Yeah, something related to https://en.wikipedia.org/wiki/Code_page_437 would be my guess.
@YenLegion Which OS did you format your SD card with, and what language was that set to?

**Comment by procount** [comment]
No response - closing
