### ISSUE TITLE
alt_image_source Allow multiple files?

### ISSUE THREAD

**Issue by matthuisman** [procount/pinn#37]
In NOOBS, you can have multiple files in repo=""
Would be great if PINN would also support this to allow for repos from Pinn + Official + Other

**Comment by procount** [comment]
I think it already can. I must check on syntax.

**Comment by matthuisman** [comment]
Also, does PINN have a way to replace the default OS file?
Seems hard-coded in?

I have made a proxy script to allow resizing maximised partitions:
https://github.com/raspberrypi/noobs/issues/139#issuecomment-286259180

With NOOBs Lite it can work as you can set repo="" in the cmdline and it will use just what is in there.

Update:
It seems no_default_source in cmdline will disable the default being used - cool.

So, now just need the multiple alt_image_source

**Comment by procount** [comment]
Just try repeating the keyword e.g.
alt_image_source=http://url1 alt_image_source=http://url2 etc.

I didn't implement the feature of allowing os-list_v3.json to be on the SD card root (which was only there for testing)

The reason it is "alt_image_source" and not "repo" is because I did it first - NOOBS didn't follow me!
