### ISSUE TITLE
How to install a OS without erasing already installed ones.

### ISSUE THREAD

**Issue by Custom9409** [procount/pinn#464]
Is there a way to install more Os without erasing other os that are already installed?

ex: Raspbian [installed] Ubuntu [going to install] Goal: Install Ubuntu without erasing Raspbian.

**Comment by procount** [comment]
Not easily, because this was never the original intention in NOOBS.
Installation creates partitions that equally share out all of your drive between the OSes, so there is no room left to install anything else. You would need to use something like GParted to shrink those partitions, but even then, the facility to add an OS into the free space you just created does not exist in PINN.
This is why I added ProjectSpaces which are able to reserve some space for future OSes (but only those that use the standard 2 partition layout of FAT & ext4). And you need to have the foresight to do it in the first place.

But if you've already installed an OS that you want to keep, then the best method is to back it up to a USB drive, using PINN's backup facility. Then install PINN on a new SD card (just to be safe, so that you keep your original OS intact until the backup is verified) and install your backup Raspbian from USB along with the new Ubuntu from the internet, plus maybe a ProjectSpace so that you can install something else at a later date.
