### ISSUE TITLE
Blank Screen Problem

### ISSUE THREAD

**Issue by ghost** [procount/pinn#607]
Hi 
I having problems with booting some Operating systems I used the Pinn online tool and a 2 Terabyte HDD The os Im having trouble booting are rpios 64 bit, ubuntu 20.10, and twister os The only Thing I tried that worked so far is lakka the led on keyboard and mouse turn on and see the raspberry pi firmware booting but after that the screen gose blank. I do not know what wrong.

**Comment by ghost** [comment]
I also used the pinn-lite that is on sourceforge

**Comment by procount** [comment]
I suppose you have no trouble viewing your monitor when you use PINN as you have managed to install several OSes?
I suspect it might be due to the new KMS display drivers in those OSes. Maybe try going back to the FKMS drivers (where F=Fake, not Full - that nomenclature always confuses me!) by modifying config.txt for each OS (you can do that in PINN's maintenance menu).
Does your monitor have a 1366x788 resolution? That can also be a problem with the KMS drivers.

**Comment by ghost** [comment]
Ok I will try that thanks my monitor as far as I've seen has not had 1366x768 all Ive used is 1920x1080 but I will try kms in config.txt thanks for helping

**Comment by ghost** [comment]
If it works I will close the issue

**Comment by ghost** [comment]
I tested it out they wer all on fkms to start I changed them to kms to se if they fix but to no avail I don't know what to try next but do you have anything I can try

**Comment by ghost** [comment]
Im just gonna close this issue now
