### ISSUE TITLE
Nothing Installs.

### ISSUE THREAD

**Issue by Connorr-RK800** [procount/pinn#619]
I was trying to install a new installation of pinns, and then when I type delete and it prepares I get 6-8 errors saying failed to download meta file, after reformating my sdcard using a laptop with a fresh install of pinns it still gives me the same message and I can't install any oses

**Comment by lurch** [comment]
> failed to download meta file

Problems with your internet connection? Or a proxy or something?
What version of PINN? Is it connected to your network via ethernet or wifi?
EDIT: And what model of Pi?

**Comment by procount** [comment]
Sometimes Sourceforge has problems, but I've just managed to download and install PIOS-lite (sic)  and Void, so no problems at the moment.

BTW @lurch & @XECDesign - I just spotted this -> https://www.bleepingcomputer.com/news/security/lets-encrypt-is-revoking-lots-of-ssl-certificates-in-two-days/ and hope we're not going to get more SSL errors!

**Comment by lurch** [comment]
> hope we're not going to get more SSL errors!

That article says it only affects certificates issued within the last 90 days, so presumably anyone who's had a certificate issued that recently will have no problem replacing it with a newer valid certificate? :shrug:

**Comment by Connorr-RK800** [comment]
> > failed to download meta file
> 
> Problems with your internet connection? Or a proxy or something? What version of PINN? Is it connected to your network via ethernet or wifi? EDIT: And what model of Pi?

RPI4 latest ver as of today ,no I've tried download the same files from the same links on my phone and there's no problem

**Comment by godzinilla** [comment]
I have enforcing this issue too today. It is a little chance to install any of the os, and literally no chance to install more than one os in a single installation (including the ProjectSpace).

Example of an error:

`Error downloading meta file http://deac-riga.dl.sourceforge.net/project/pinn/os/raspios64/marketing.tar`
`Error downloading meta file http://deac-riga.dl.sourceforge.net/project/pinn/os/raspios64/os.json`
`Error downloading meta file http://deac-riga.dl.sourceforge.net/project/pinn/os/ProjectSpace/os.json`

Looks like no access to these files.

**Comment by procount** [comment]
This looks like a sourceforge error.
I experienced something similar, which incidentally was also using the deac-riga mirror, but it was just temporary.

**Comment by procount** [comment]
I have raised a ticket with SourceForge.

**Comment by godzinilla** [comment]
> I have raised a ticket with SourceForge.

Thanks. Can images be download from the sourceforge and loaded to the PINN directly (multiple images)? Or we need to wait for sourceforge to fix this issue?

**Comment by procount** [comment]
https://github.com/procount/pinn/blob/master/README_PINN.md#download

EDIT: Hmm, that link doesn't always point to the correct place, so instead try:
https://github.com/procount/pinn/blob/master/README_PINN.md#archival-menu

**Comment by godzinilla** [comment]
> https://github.com/procount/pinn/blob/master/README_PINN.md#download
> 
> EDIT: Hmm, that link doesn't always point to the correct place, so instead try: https://github.com/procount/pinn/blob/master/README_PINN.md#archival-menu

Not sure why but I cannot select my USB drive or sd card in sd reader under Archival menu. Both can be selected under Main Menu but on under Archival...

**Comment by procount** [comment]
You must create an `os` folder on that drive. Make sure it is FAT32 or EXT4 formatted. I think NTFS will also work but is not preferred.

**Comment by godzinilla** [comment]
> You must create an `os` folder on that drive. Make sure it is FAT32 or EXT4 formatted. I think NTFS will also work but is not preferred.

Of course, I am a total moron today, didn't read the whole instruction ;) Downloading in progress, or it looks like it is downloading - no progress bar, all elements in window grayed out.

Edit:
So after about 10 minutes of wait I have removed the usb drive, connected it to the Windows PC and found, that only some small files were downloaded for each selected OS. In one folder there was also an error.log file with the error message same as I paste above. It looks that we need to wait for the fix with connecting to the sourceforge servers for both downloading and installing oses.

**Comment by procount** [comment]
You can download all the files for each OS manually from sourceforge to your USB. You should be able to see the required folder structure on the USB now. When you select a file to download from their webpage, there is a button called "Problems Downloading?" Here you can change the mirror you download the files from. Maybe you will have more luck if you choose a mirror close to you.

**Comment by godzinilla** [comment]
> You can download all the files for each OS manually from sourceforge to your USB. You should be able to see the required folder structure on the USB now. When you select a file to download from their webpage, there is a button called "Problems Downloading?" Here you can change the mirror you download the files from. Maybe you will have more luck if you choose a mirror close to you.

No option to download all the files in the directory?

**Comment by procount** [comment]
I don't think so. That's one reason why I added the download feature in PINN. PINN shoudl autoresume though. Maybe you could try it multiple times to try and get a different mirror?

**Comment by godzinilla** [comment]
The problem is connected with not accessible files by the sourceforge side. Let's check for an example the LineageOS 19 ATV:
`https://sourceforge.net/projects/pinn/files/os_next/lineage19-rpi4-atv/slides_vga/`
these files are not accessible from any mirror. The same for `lineage19-rpi-atv.png`.
Maybe these files are simply not exists on the server(s)?


BTW I have found a solution for downloading all files from the SF directories:
`https://stackoverflow.com/questions/39668291/download-whole-folder-from-sourceforge`
Under the `How to download all files from a particular folder in Sourceforge on Windows 10:` comment.

**Comment by procount** [comment]
I tried it and failed to download 1.jpg.
But then I changed the mirror to Net Cologne and it downloaded. So I think it is intermittent. or mirror based.

EDIT: Good find on downloading a folder, btw.

**Comment by godzinilla** [comment]
> I tried it and failed to download 1.jpg. But then I changed the mirror to Net Cologne and it downloaded. So I think it is intermittent. or mirror based.
> 
> EDIT: Good find on downloading a folder, btw.

You were right, I finally managed to download the pictures that interest me. But I am still looking for the directory of Raspberry Pi OS Lite... The folder name generated by PINN is `Raspberry_Pi_OS_Lite_(32-bit)` but there is no such folder on SF.

**Comment by procount** [comment]
You need to look on the NOOBS server for that one. PINN uses 4 different repos.
https://downloads.raspberrypi.org/raspios_lite_armhf/

**Comment by godzinilla** [comment]
> You need to look on the NOOBS server for that one. PINN uses 4 different repos. https://downloads.raspberrypi.org/raspios_lite_armhf/

Thanks. So I have finally installed all my images. Installation passes without problems but there is no any system available in the boot menu, even under the Maintenance menu. All partitions were created and files are available (under the windows).

**Comment by procount** [comment]
Sourceforge have removed a mirror from their rotation so hopefully that will help with internet installation.

If there are no systems in the boot menu, then something must have gone wrong somewhere.
Can you post a copy of `installed_os.json`.?
It is on /dev/mmcblk0p5 which is mounted as `/settings` in PINN's shell.

**Comment by godzinilla** [comment]
> Sourceforge have removed a mirror from their rotation so hopefully that will help with internet installation.

So they will fix it?

> If there are no systems in the boot menu, then something must have gone wrong somewhere.
> Can you post a copy of `installed_os.json`.?
> It is on /dev/mmcblk0p5 which is mounted as `/settings` in PINN's shell.


File is empty.

**Comment by godzinilla** [comment]
![IMG_20220201_183909__01.jpg](https://user-images.githubusercontent.com/77450480/152021243-2c6368fe-ec3e-4185-922b-601ddc28ebb1.jpg)
![IMG_20220201_183918__01.jpg](https://user-images.githubusercontent.com/77450480/152021261-a2e5661c-89e9-4bc6-a749-4d9d7030a552.jpg)
![IMG_20220201_183928__01.jpg](https://user-images.githubusercontent.com/77450480/152021297-24910720-c580-412f-9a80-394322254f5d.jpg)

This is the structure of /os folder on my USB drive from which installation process were begun.

I have literally downloaded all files from the SF to the corresponding folders.

For the ProjectSpace folders all files were copied from one directory to others.

**Comment by procount** [comment]
By removing the faulty mirror, hopefully sourceforge have fixed it, unless you are telling me you still have problems.

if installed_os.json is empty, then PINN does not think you have installed any OSes.

It looks like you have downloaded the OS files correctly to your USB drive.
After downloading them, was the icon to the right of each OS in PINN showing the USB symbol instead of the ethernet symbol, indicating the OS is sourced from the USB drive? Did you then install from the USB drive to your SD card?
Having no `/settings/installed_os.json` suggests you haven't, or there was some other error.
You haven't included anything about what was installed to your SD card or its structure, so it's difficult to diagnose. You can't do this from Windows. Have a look at https://github.com/procount/pinn/wiki/Troubleshooting

**Comment by godzinilla** [comment]
> By removing the faulty mirror, hopefully sourceforge have fixed it, unless you are telling me you still have problems.
Not testes yet, still I messing up with my downloaded images.

> It looks like you have downloaded the OS files correctly to your USB drive. After downloading them, was the icon to the right of each OS in PINN showing the USB symbol instead of the ethernet symbol, indicating the OS is sourced from the USB drive? Did you then install from the USB drive to your SD card?
Yes and yes.

I made some testing and found that issue is somehow related to the LinegaeOS19 ATV image. If you made a single install with ATV and ProjectSpace (one space) images are not visible in the boot menu, but just after installation images are still checked and signed as INSTALLED and the Maintenance list contains only PINN image.

If you first install the single ProjectSpace, and after restart the ATV image - both images are installed, ATV is bootable, Maintenance menu contains all three images. Everything works as expected.

I have trying to install more than one ProjectSpace images, and after restart the same number of ProjectSpace + ATV image - without success.

I was trying to install following images:
- LineageOS 19 ATV,
- LineageOS 19,
- RPi OS 64 bit,
- RPi OS 32 bit Lite,
- piCorePlayer,
- couple ProjectSpace images.

I am able to install all listed images without ProjectSpace. When the ProjectSpace is added to the installation process - described issue exists. I have checked my SD card and looks like related partitions are created correctly, data exists on it. But no boot menu and empty `/settings/installed_os.json` file.

**Comment by godzinilla** [comment]
Finally, after reformating my SD card, downloading images using the PINN (it is working now) and installing in single installation - everything working as expected.

So looks like my issue comes from incorrect, manually downloaded images and/or messed up sd card

.![IMG_20220202_100524__01__01.jpg](https://user-images.githubusercontent.com/77450480/152124556-4b462642-db90-45cb-8309-84c7365b43db.jpg)

**Comment by procount** [comment]
Glad it's sorted for you.
Feel free to close this issue.
