### ISSUE TITLE
I cant log on pinn ui after enabled vnc option

### ISSUE THREAD

**Issue by lef1337** [procount/pinn#633]
After enabled vnc in pinn pi4 boots in OS any way to disable it neither i can log with vnc on port 5900

**Comment by procount** [comment]
You don't mention if you are using vncinstall or vncshare. I suggest you use vncshare because you can still see what's happening on a local monitor during testing.
With VNC often PINN will timeout before VNC is enabled. So you should use the forcetrigger option in conjunction with remotetimeout, See https://github.com/procount/pinn/blob/master/README_PINN.md

**Comment by lef1337** [comment]
Thank you it worked
