### ISSUE TITLE
Support for Piper Computer Kit

### ISSUE THREAD

**Issue by myxxmikeyxx** [procount/pinn#655]
Can you add support for piper computer kit OS
https://www.playpiper.com/pages/instructions-to-update-your-sd-card

**Comment by myxxmikeyxx** [comment]
Never mind. I found it. I just needed to update my PINN to the latest one. Sorry for any trouble.
Every time I try to to install it, it crashes to tty interface and says 
`Starting system message but: done
                                                          Recovery application crashed
Starting shell
sh: can't access tty;  job control turned off
/sys/class/block # _`

**Comment by procount** [comment]
I just tried installing PlayPiper OS on a 3B+ and it installed and worked fine. What SD card size are you using? I had trouble running it in 8GB but it worked fine as the only OS on a 16GB card.

**Comment by myxxmikeyxx** [comment]
I am using a 32GB card.
I am trying to do raspberry pi OS (32 or 64, not the recommended software one), and the PlayPiper, but it keeps failing.
Even when I try doing the PlayPiper alone.
I am selecting it from the Education tab.

**Comment by myxxmikeyxx** [comment]
Can I cat out crash log? If so where might it be?

**Comment by lurch** [comment]
https://github.com/procount/pinn/wiki/Troubleshooting

**Comment by procount** [comment]
@Lurch - you're on the ball today - you keep pipping me to the post! 🤣

**Comment by myxxmikeyxx** [comment]
Here is my `dmsg | less` output. 
I saved it to a usb
[dmesg.log](https://github.com/procount/pinn/files/8653332/dmesg.log)
.

**Comment by procount** [comment]
Nothing much useful in there.
Step 3 to grab the debug log might be more useful.

**Comment by myxxmikeyxx** [comment]
My debug log is attached.
It might show that I started installing raspberry pi OS 64 bit because I need one working SD card right now but I have another one that I can use for testing. It has been happening on both SD cards on the same pi.
[debug.log](https://github.com/procount/pinn/files/8661196/debug.log)


P.S. Thank you both @procount @lurch for all the help. Sorry for the trouble.

**Comment by myxxmikeyxx** [comment]
Could my SD card be to small to hold raspberry pi OS (64 or 32) and have playpiper on it?

**Comment by procount** [comment]
A 32gb sd card should be fine. I ran playpiper on a 16gb card successfully.

The debug log is temporary and is lost once the power is removed. So you need to capture the log immediately after the problem has occurred. In your case when the "recovery application has crashed" message comes up. Hopefully it will still be workable enough to capture the log of playpiper failing.

When does that message occur? When installing the boot or root partition, before or after the "os installed successfully" message, or when you try to boot into playpiper?

**Comment by myxxmikeyxx** [comment]
It happens right after I click install and through those prompt saying are you sure. I will try to get the logs here soon.

**Comment by lurch** [comment]
Are you using a reliable branded SD card, or are you using a cheap no-name card? If it's the latter, it might be a "fake" card, and PINN is crashing when trying to create the partitions? :shrug:

**Comment by myxxmikeyxx** [comment]
@lurch SanDisk Extreme Pro, its the same brand and type I use at home and at work and for most everything besides some super cheap 8GB ones that I do basic testing on at home.

**Comment by myxxmikeyxx** [comment]
attached is the debug log
[debug.log](https://github.com/procount/pinn/files/8687025/debug.log)

**Comment by procount** [comment]
Can you post a copy of your "/settings/os/playpiper/partitions.json" file, please?
I'm wondering if this is a sourceforge mirror problem. i.e. the file you are downloading is not the same as the one I download because they come from different mirrors.

**Comment by myxxmikeyxx** [comment]
If the file is coming from source forge then that is being blocked by my works web filtering.
I thought you got the file from playpiper's site like the raspberry pi one. I guess I will have to take it home and do it or make an IP exception for the raspberry pi temporally.

Thank you for all the help. Sorry for the trouble. I never had this problem when using the raspberry pi img from PINN so it never occurred to me to think that it was being blocked. 

Would I be able to download the img manually and put it in a folder for it to install it? if so where are the directions for how to do that?

**Comment by procount** [comment]
That would explain a lot! 😄 

PINN does not install image files because it needs to use a different partition layout to the one stored in a .img file.
Each OS needs to be converted to a different format consisting of a tar file per partition and several meta-files to inform PINN how to install it (plus a nice slideshow, icon etc). RPT do this automatically for Raspberry Pi OS and are hosted on the RPT website, along with some other OSes that are installed by NOOBS.
Some other OSes are already provided in NOOBS format and hosted by their maintainers, but the rest are converted by myself or Matt (for mostly retro games and media center OSes) and hosted on sourceforge.

Yes you can download an OS (say at home) and install it locally from USB stick (say at work), but it is a whole folder of files, not just a single image file. You will find instructions in https://github.com/procount/pinn/blob/master/README_PINN.md#local-images-on-usb-stick and https://github.com/procount/pinn/blob/master/README_PINN.md#download. I suggest using the download feature in PINN to download an OS, but make sure your USB stick has an 'os' folder in its root first otherwise it will not be recognised.

By the way, the rest of that README_PINN.md document describes PINN's functionality, so is a good read to get the best out of it.

**Comment by myxxmikeyxx** [comment]
Thank you so much. I will have to take a look at it. I tried it out a couple of years ago but I have slept a few times since and I never got it working properly. It was all my errors but I have messed with Linux more and command line and partition so I might be better equipped to understand it now. 

Thank you so much for your time and effort! Sorry for all the trouble.
