### ISSUE TITLE
recalbox-pi4

### ISSUE THREAD

**Issue by SerdarARIKAN** [procount/pinn#694]
recalbox installation is return "Recalbox_-_Pi4 needs a partition label of SHARE which is not available" error and installation does not continue. 

My recovery.cmdline file is;
runinstaller quiet ramdisk_size=32768 root=/dev/ram0 init=/init vt.cur_default=1 elevator=deadline no_group no_default_source select="allnetwork" disablesdimages alt_image_source=http://pinn.mjh.nz/os_list.json?dietpi_64=2198&batocera_rpi4=3996&lakka_rpi4_64=3130&recalbox-pi4=7742&retropie4=3426&lineage19-rpi4=7532&lineage19-rpi4-atv=7532&libreelec_rpi4=1594&moode=3901&osmc_pi4=2762&picoreplayer64=691&volumio=3373&xbian_rpi3=1431&datapartition=8192 loglevel=2 sdhci.debug_quirks2=4

**Comment by procount** [comment]
Recalbox REQUIRES one of its partitions to be called SHARE, but that partition name has already been allocated (probably by Batocera, which also requires it, since Batocera and recalbox are closely related). It is not possible to have 2 partitions with the same name, so PINN prevents the second one from being installed.

This means you can't have Batocera and Recalbox on the same SD card. It is a constraint of both of those OSes wanting to use the same name for their partition.

**Comment by retroNUC** [comment]
Just ran into the same issue here, and found this post.

For the record, hitting this error also prevents all future queued OS installs from happening, rather than just failing this one and continuing the queue. Possible to make this fail gracefully, or add the known clash into the UI in order to prevent these two both being selected?

**Comment by procount** [comment]
> For the record, hitting this error also prevents all future queued OS installs from happening, rather than just failing this one and continuing the queue. 

That shouldn't be the case; the remaining OSes should continue to be installed.

> Possible to make this fail gracefully, or add the known clash into the UI in order to prevent these two both being selected?

It may be possible to do some pre-checks, I'll look into it for a future version.
