### ISSUE TITLE
New screen blank display for installed & working PINN, number keys don't help

### ISSUE THREAD

**Issue by ajl199** [procount/pinn#716]
Sorry, me again with more of a support request than an issue.

Everything's been going well up to this point, multi-booting BBN, OpenPlotter, and Raspberry Pi OS via PINN. Then I found a rather nice monitor on ebay: HDMI, 12V powered and in a rubber housing - ideal for the boat. The problem is, it seems to be rather touchy about the signal it gets and PINN doesn't show up.

I see the initial kernel messages, then the screen blanks out while PINN does its thing, then I get the OS booting (which prior to finding the solution also blanked between kernel messages and X). I've finally got it working in RPiOS with a kernel parameter for KMS, but I don't think that's applicable to PINN. I've tried repeatedly pressing 2 in an attempt to trigger HDMI safe mode while PINN's there behind the dark screen, in accordance with the readme, but that doesn't help.

Is there any way to set framebuffer parameters for an existing PINN installation? I can access PINN's files once booted, and can still see PINN's interface if I connect the Pi to a different monitor.

**Comment by ajl199** [comment]
I've partially fixed my own problem, by adding the following to config.txt:

hdmi_safe=1
hdmi_force_hotplug=1
hdmi_group=2
hdmi_mode=73

2,73 match the kernel parameter which keeps KMS happy.

Now, I get the rainbow screen, and the screen of coloured curves. But, where the window with OS choice in it should be on the latter is just an empty black square. Boot then proceeds automatically to the previously loaded OS.

Any ideas?

**Comment by procount** [comment]
There are 3 methods of driving a Raspberry PI display: Legacy, FKMS and KMS.
Raspios is now using KMS and ignores all the config.txt settings.
Conversely, PINN still uses legacy and uses config.txt settings, as you have found.
Both methods parse the EDID data from the monitor using different algorithms so can come up with different resolutions, especially if the EDID data is not correct.
The PI4 also complicates matters because it must have a horizontal resolution that is divisible by 8 (I think), which is why 1366x768 doesn't work with it.

This is not a PINN specific issue per se, but more to do with the VC4 legacy drivers and the monitor. I've never seen such an issue, so I am short on additional ideas to what has been proposed to you already on the forum.

Have you tried lower resolutions, like mode 2,28 (1280x800) ?

If you have some sort of visible screen, you could try troubleshooting it in PINN's cmd shell.
Press Ctrl-Alt-F2 and login with root/raspberry to get to the shell (To return to PINN's display, just swap back with Ctrl-Alt-F1)
In the shell you could try some of the suggestions from https://elinux.org/RPi_Configuration under the section "Which values are valid for my monitor?". But note that you don't need to add the path to tvservice and it is in a different location to where that webpage suggests.
PINN does not provide edidparser, so you would need to copy the resultant edid.dat file to raspios and decode it on there.

**Comment by ajl199** [comment]
Thank you, I'll give that a go. The latest interesting thing is that it's hdmi_safe which is making what does show up show up, but according to https://elinux.org/RPi_Configuration hdmi_safe "is the same as the combination of: hdmi_force_hotplug=1, hdmi_ignore_edid=0xa5000080, config_hdmi_boost=4, hdmi_group=2, hdmi_mode=4, disable_overscan=0, overscan_left=24, overscan_right=24, overscan_top=24, overscan_bottom=24", but 

hdmi_safe=1

works, while

hdmi_force_hotplug=1
hdmi_ignore_edid=0xa5000080
config_hdmi_boost=4
hdmi_group=2
hdmi_mode=4
disable_overscan=0
overscan_left=24
overscan_right=24
overscan_top=24
overscan_bottom=24

doesn't.

Also, if I click a mouse button while the windowless PINN is showing, it fires up rescue mode correctly, and then lets me exit to the boot menu. I think the boot menu not showing might be more of a timing issue than anything else.

**Comment by ajl199** [comment]
I was right. Setting bootmenutimeout=30 in recovery.cmdline provides it with enough time to display the boot menu after the screen's clicked in. Results: not necessarily pretty, but functional which is what matters at the moment.

My only remaining question is whether there are any of the component options of hdmi_safe above which PINN won't read from config.txt? If not, I guess the elinux documentation is out of date and I'll need at some point to track down what hdmi_safe actually replicates.

**Comment by procount** [comment]
LIke I said above, this is nothing to do with PINN. 
PINN does not read config.txt.

Config.txt is read by the VC4 firmware to configure the display (and other things) before the Linux kernel is even loaded.
PINN just finds out what size the screen is set to and adjusts itself to fit.
The only time PINN tries to configure the display resolution is when you press one of those 4 number keys, and even then it just uses tvservice.

But anyway, I'm glad you got it working sufficiently.
