### ISSUE TITLE
Regarding Kali & RPi 4 8gb

### ISSUE THREAD

**Issue by jeff-jm** [procount/pinn#717]
Hello, I'd first like to thank you for your contribution towards this project.

I am brand new to PINN so I apologize if this is a silly question, but I noticed Kali is not appearing in the list. 

Is it normal for the to fluctuate? Should it reappear soon? I was wondering if it was a problem with my 8gb RPi 4 or something unrelated.

Thanks.

**Comment by procount** [comment]
A version of Kali from 2020 is available for the Pi4.
You should find it under the General tab.

The list of available OSes is downloaded from the various servers available on the internet.
If you are not getting a list of OSes, please check your internet connection and make sure you have an IP address showing in the title bar. Do you get any error messages when PINN starts indicating it can't access any of the OS lists?

PINN will filter the OS list to only shows OSes that are suitable for your RPi model, but as you have a Pi4 8 GB, this should not be an issue.

**Comment by jeff-jm** [comment]
Hey @procount !

I do not receive any errors when loading the list of OSes from Internet.

I checked again an Kali still seems to be missing from the general tab. The available OSes for me under "General" are:
- Raspberry Pi OS (3 Versions)
- TLXOS (1 Version)
- Lineage (7 Versions)
- twister (1 Version)
- ubuntu (3 Versions)
- Ubuntu Mate (3 Versions)
- gentoo64 (1 Version)
- nspawn64 (1 Version)

I tried installing it manually from a USB to try to see if PINN would recognize it locally, but could not get it to work either.

Let me know if there is anything you recommend I try, thanks again!

**Comment by procount** [comment]
You didn't mention Manjaro or RIscOS either in your above list.
This is what I can see:

![pinn-kali](https://user-images.githubusercontent.com/4853137/227792768-4e92ac76-eb8c-4d0b-9c56-7fbf0df8a254.jpg)

and there are a few more beneath that if I scroll down. But you can see that 2 versions of Kali are available.

What is your recovery.cmdline?

Can you post the contents of your debug log? Please see https://github.com/procount/pinn/wiki/Troubleshooting for details on how to capture this, particularly steps 5 or 6.

**Comment by jeff-jm** [comment]
Hey @procount , 

Thank you for your continued support.

After looking at your screenshot, I saw your destination drive was a SD card, where as I was trying to use an External USB Drive.

I installed PINN on a USB Drive, and was trying to install additional operating systems on the same USB Drive. After trying an SD Card, all of the OSes in your screenshot above appeared, they only disappear when my destination drive is a USB Drive.

Is this to be expected? Should I try to buy a 64 gb SD Card instead of USB Drive? I apologize for the lack of knowledge as I am new to RPi & Linux distros in general. 

I can try to get you the recovery.cmdline and the debug log if you still think it is relevant, let me know!

THanks so much.

**Comment by procount** [comment]
No need to send anything more - I think we found the answer. Apologies for not thinking of it earlier.
Not all OSes are capable of being installed on a USB drive due to the way they reference their partitions, (This is true whether you use it with PINN or not).

The version of Kali I use is quite old now, being from 2020 and is marked as not supporting USB.
It could be that more recent versions can be installed to USB drives, but it would take some time to convert and test them.
You could wait until I can find some time to do that, or if you need an immediate solution a larger SD card would be appropriate.

**Comment by jeff-jm** [comment]
@procount ,

Thank you so much, your support was prompt and extensive.

I will go ahead and close this issue as you have clarified everything!

Apologies again for my lack of knowledge and research, wishing you the best.

**Comment by procount** [comment]
The good news is that Kali 2023.1 can run from USB. but I still need to see if it will convert to PINN format.

**Comment by jeff-jm** [comment]
Awesome!

I will be looking forward to upcoming updates!

I looked around but can't seem to find any donation requests or information regarding the project. I have to ask - is this project run by donations? Or are you a hobbyist/enthusiast yourself just doing it for the community? I am super impressed by the functionality and usability of PINN!

Some other questions I had (if you find time, not important):
- I am just getting into Raspberry Pi things, I mainly want to use it as a tool to get familiarized with Linux distros. 
- I initially planned using PINN on a bootable USB Drive, but as I have discovered it seems to be more simple to use a Micro SD card.
- Are there advantages to using a Micro SD card instead of USB 3.0 Drive? Would an external SSD be a better option?
- Should I avoid using a bootable USB 3.0 and buy a bigger Micro SD Card instead? I only have 30gb. 

Thanks so much again!

**Comment by procount** [comment]
A couple of people have asked about donations in the past. Perhaps one day I should facilitate that somehow. :smile:
But I am just an enthusiast who liked the idea of the original NOOBS program and used it to learn how to program in Linux. 
Once I understood how it worked, I extended it in ways that exceeded the original NOOBS remit and turned it into PINN.
I had some very kind help from the RPF on the way :smile:
To answer your points:
 - Yes, that's what I did
 -  Simple -yes. All OSes can run on the SD card as it was all that was available at the start. Only later did USB boot become a reality and it took a while before some OSes were made compatible with USB boot. Some still aren't.
 - In general, SD cards tend to be slower and less reliable than external USB drives, although I have hahd very few problems with them. Many people prefer to use external USB drives because of that, but it depends on whether the OS you want to use supports it. Many recent ones should do by now. In general, external USB SSD drives are the fastest over flash drives and HDDs. You will get no advantage using an NVME drive over an SSD because the RPi is not fast enough to take advantage of the extra speed. It is possible to run PINN in a hybrid mode where the Boot partitions are stored on the SD card and the root partitions are stored on the USB drive. This allows more varieties of OS to run from USB, even if the RPi does not support USB Booting (pre-3B). As only the boot partitions are stored on the SD card, the SD card need not be so big and you get the advantage of running most of the OS from USB.
 - Try Hybrid booting - it might be suitable for you to start with without any additional outlay.

Some caveats to be aware of:
- PINN only works with MBR partitions, which limits the drive size used for storing the OSes on to a maximum of 2TB. Additional data drives could be of GPT type to break the 2TB limit, however.
- PINN OSes must be bootable from the RPi firmware. If they use UEFI, U-Boot, Grub, lilo or anything else, that bootloader must be removed first. It is not always possible to do that.

**Comment by procount** [comment]
Kali64 (2023.1) is now available in PINN.

**Comment by jeff-jm** [comment]
> Kali64 (2023.1) is now available in PINN.

Awesome! I now see it is available to install via USB!

I can't thank you enough for all the information you provided about the different booting options. I figured out how to do the "Hybrid Booting" , and am now able to install all the OS's on my USB drive!

Thanks again for everything, I seriously respect and appreciate the work you and others have put into PINN!

**Comment by procount** [comment]
You're very welcome.
