### ISSUE TITLE
How to add custom OSes?

### ISSUE THREAD

**Issue by Tman564wsDEV** [procount/pinn#748]
So I want to make a pinn fork that has some OSes that I would like, and after I looked at the os_list_v3.json I was like oh, this will only take a hour or so, I stayed up until 2AM And I still have to Fix the partitions_setup.sh. And some other stuff.
Can you please help?

The OS that I want to add right now is Parrot Security OS (Or ParrotOS for short)

**Comment by procount** [comment]
Hmm, I don't think you mean a PINN FORK - that implies you are going to make your own version of PINN by modifying the source code and rebuilding it. I don't think that is what you need. If you just want to change the list of OSes by adding your own etc, then you just need to modify the repo_list, repo or alt_image_source options. Have you read https://github.com/procount/pinn/blob/master/README_PINN.md?

Also check out my Wiki on github as that includes a couple of tutorials on how to convert your own images.
I'm afraid that converting an OS for multi-boot installation by PINN is not always an easy operation, since many OSes are unique and are not originally designed to work off different partitions. It does require a fair bit of knowledge of partitions, formats and boot configuration. The tutorials cover most standard OSes that are similar to Raspberry Pi OS, but may need adapting for other OS types.

I have a few issues to sort out and some other OSes to upgrade first. I may have time to look at ParrotOS after that.

**Comment by Tman564wsDEV** [comment]
Ok I will check it out

**Comment by Tman564wsDEV** [comment]
Also i meant to say pinn-os

**Comment by Tman564wsDEV** [comment]
Also where is your wiki?

**Comment by procount** [comment]
It is on this github. There is a link at the top of this issue page. Specifically https://github.com/procount/pinn/wiki

**Comment by Tman564wsDEV** [comment]
Ok, its too much work, But thanks!
