### ISSUE TITLE
Cannot boot into Volumio after OS update

### ISSUE THREAD

**Issue by Hiforever** [procount/pinn#782]
I'm currently using Volumio relaese 3.546.  Once I update to OS to latest version within Volumio, Pinn fail to boot into Volumio again be it release 3.569 or 3.601,  

Update within Volumio OS works perfectly in the past.

**Comment by procount** [comment]
Wihtout looking into this in detail, please try this -> https://github.com/procount/pinn/blob/master/README_PINN.md#re-run-partition_setupsh to see if it works.

**Comment by Hiforever** [comment]
tried running the fixes includiing partition_setup.sh.   Still not working

**Comment by arlo-infinity** [comment]
@Hiforever I had the same problem updating from an even older version 3.2xx . I may be too late for you, but I will respond anyway in case it helps someone else.

It's possible to do the update but it requires some slightly technical "partition surgery" to get it to work. Volumio has 3 partitions "boot", followed by "volumio", followed by "volumio data" that will show up somewhere in the extended partition that PINN creates depending on where it is located in your OS list in PINN.  Note that "boot" may be called "boot1" or "boot2" etc.. when mounted externally again because of the ordering of OS in PINN.  Basically, the "boot" partition for Volumio is 64MB but after the update to 3.569 or 3.601 it needs more than 64MB of space, so you need to backup your current "boot" partition and the neighboring "volumio" partition, delete both of them, create a new "boot" partition that is say 128MB in size (64 MB more), create a new "volumio" partition that fills all available space before the "volumio_data" partition (it will be 64MB smaller than before but no big deal as it is quite large), restore your backups of "boot" and "volumio" to the newly sized partitions respectively, and make sure to rename the volume labels back to "boot" or "boot1" or whatever it was originally.   

I used the Windows Freeware version of DiskGenius to do this as it is able to backup and restore individual partitions from a drive with many partitions, and is also able to delete and create new partions.   If you want to try this and are having trouble with DiskGenius just let me know and I can give some pointers.  Advanced users could also do this with GParted under linux using dd to backup/restore your partitions.   Actually, both DiskGenius and GParted have "resize partition" and "move partition" features that can be used to move space from one partition to another without creating a backup, but it's more risky and I think the backup-delete-restore method is safer.  If you have access to Windows I'd really recommend using DiskGenius as it avoids the command line entirely.

Once you have completed the partition surgery you should be able to boot into Volumio as per normal, the update should work without failing, and you won't lose any of your playlists or other data.

Hope this helps.

**Comment by procount** [comment]
Thanks for providing a solutuon. It does seem to work.
I have asked Matt to increase the default size of the boot partition to prevent this from happening on new installationz.

**Comment by Hiforever** [comment]
Thanks for the solution.  OS update is working now after resizing the Volumio boot partition to 128MB

**Comment by arlo-infinity** [comment]
> Thanks for providing a solutuon. It does seem to work. I have asked Matt to increase the default size of the boot partition to prevent this from happening on new installationz.

No problem.  I realized what the issue was a few weeks ago once I found this the thread [Upgrade to v3.569 not possible](https://community.volumio.com/t/update-to-v-3-569-not-possible-all-you-need-to-know/63663) but I just had time to post it yesterday. Matt was super fast and has already updated the partition size to 120MB and upgraded the Volumio version to 3.616, so at least this boot partition size issue should be ok for a little while.
