### ISSUE TITLE
Update from 3.9.1 to 3.9.2 failed

### ISSUE THREAD

**Issue by JanSykor** [procount/pinn#817]
Hello @procount 
I have update failed message on RPi3 and RPi4.
Here is picture of log:
![17167176671083034440283965685486](https://github.com/procount/pinn/assets/23189392/1a828692-cec2-4456-95b8-ca5bf7405dee)
If you need aby other detaily, please let me know.

On Pi5 update was OK.
Thanks
Jan

**Comment by procount** [comment]
Thanks for the report.
It's failed because there is not enough space on the RECOVERY partition for the new version. About 1.5MB less. Not sure why - did you have some additional files on there?  Could you list what is left on there now (ls -alF /mnt)?
I tested the rollback if there is not enough space, but your rollback failed for some reason. 
(If you haven't rebooted, you can copy your files from /settings/mnt to /mnt.)

EDIT: Sorry, just noticed this was 3.9.1 to 3.9.2. I need to do some more checks on that.

**Comment by JanSykor** [comment]
Hi @procount 
Here is logs and file list from RPi3
Rollback not failed - installation was not damaged and I have still 3.9.1 version - just installation failed.
[logs.zip](https://github.com/procount/pinn/files/15451183/logs.zip)
No effect depend keyboard - same result in english nor czech
Thanks
Jan

**Comment by mbernardi1961** [comment]
I have the same issue using a RPi4. 

Now working perfectly: Thank You

**Comment by procount** [comment]
Updates from 3.9.1 to 3.9.2 should now work ok, if you'd like to retry it.

**Comment by JanSykor** [comment]
Nice job @procount . Thank you
Small wallpaper selected and language was necessary select again (english and then again czech) to apply last language pack.
Working perfect now on Pi3 And Pi4.
Jan
