### ISSUE TITLE
CP437: Invalid Argument

### ISSUE THREAD

**Issue by Mace1482000** [procount/pinn#833]
**Describe the bug**
When getting ready to install selected OS's once you click the install button and set the partition sizes then the OK button you'll immediately receive a error stating "Error reading existing partition table" checking the debugging log I'll see it the only error being a "CP437: Invalid argument. Causing any select OS or further progress from proceeding. 

**To reproduce**

1. Select desired OSes
2. Click Install
3. Adjust or leave partition tables balanced by default
4. Click OK

**Expected behaviour**
Add a clear and concise description of what you expected to happen.

**Actual behaviour**
Add a clear and concise description of what actually happened.

**System**
Raspberry Pi 4B 4Gb
SK Hynix 400Gb SD card
Generic 4Gb USB Stick

PINN v3.9.2

**Logs**

**Additional context**

To troubleshoot I've tried multiple things. 

Reformatting both the USB and SD Cards to Fat32 and reinstalled PINN

Tried resizing partitions and checked for error's

Adding IOSChar UTF8 & IOSChar 8859-1 Character Sets to the cmdline.txt file and saving

Used other USB sticks and SD cards

Attempted to install other OS's or other OS's alone. 

Check to ensure there was no issues accessing the SD card such a bitlocker or other security locks that could cause it to fail to partitions. 

Nothing I've tried so far has seemed to have affected the behaviour or changed how its been acting.

**Comment by procount** [comment]
Can you post the debug log with the error in it, please?
How did you install PINN? I suggest using RPi Imager if you haven't already. Or if you have a keyboard and wired ethernet connection use the built in net install.
I suggest you use h2testw (on windows) to check your 400GB SD card.

**Comment by Mace1482000** [comment]
It is hardwired with an ethernet cable and I used the Pi Imager to install PINN 

[debug.txt](https://github.com/user-attachments/files/16810702/debug.txt)

I'll post the results of the H2testw after it completes. It looks like its gonna take some time.

**Comment by Mace1482000** [comment]
SD Card Results

Test finished without errors.
You can now delete the test files *.h2w or verify them again.
Writing speed: 32.7 MByte/s
Reading speed: 79.8 MByte/s
H2testw v1.4

**Comment by procount** [comment]
OK, thanks. So your SD card is genuine (many large size cards aren't).

The "CP437: Invalid argument" message is just a warning. it is from the fsck.fat function, which only seems to be called if you decide to do a file system check from the Fixup menu option. It is not relevant here. But this is being run on SDA1

What is relevant is the "Error reading existing partition table" message, but the debug.txt does not appear to have captured any of the logs around the installation. (The debug log is volatile, so you would need to repeat the installation,then immediately drop to the command shell and copy the log).

So at the moment I can only guess what the problem is as this error message comes from a standard program (like parted).

Looking at the debug log, it shows you are running PINN from a USB drive (I assume your 4GB USB stick), but this is far too small to install anything on. So I guess you are trying to install to your 400GB SD card? This may be where you problem is.

Forget your USB stick - you don't need it. Use Rpi Imager to install PINN onto your 400GB SD card. (make sure you use a suitable SD card reader). Boot PINN and install your OSes onto your SD card.

(Aside for info: A long time ago before USB boot was possible, when one wanted to install OSes to USB it was necessary to install PINN onto an SD card and then install OSes to a USB stick. In this case, the OS boot partitions were still on the SD card and only the root partitions were on the USB stick. This created a hybrid system and meant it was always necessary to have the SD card inserted. 

You seem to be doing it the other way round, where you install PINN and OS boot partitions on the USB stick and want to install the root partitions to the SD drive. As PINN has not been installed to the SD card and partitioned it, the SD card may not have been partitioned appropriately, hence the error).

**Comment by Mace1482000** [comment]
Seemed to do the trick and is working now. However I'm faced with another unrelated issues due to number of partitions. I'll create a separate issue if that one if I don't figure this one out. Thanks for the help!
