### ISSUE TITLE
Auto boot into os?

### ISSUE THREAD

**Issue by Haris1977** [procount/pinn#98]
Is there any option to auto boot into a specific os (e.g openelec) but only after the 10 second booting time (in order to have the possibility to change os)?

Berryboot already has this option (as favorite)

**Comment by procount** [comment]
Yes, that's the 'sticky default boot' option. Tick the box next to openelec on the boot selection dialog.

**Comment by Haris1977** [comment]
I ve already installed 3 os's now:(

Can i enable "sticky default boot" option by entering the recovery mode (PINN interface)? Or do i have to install all os's again?

**Comment by procount** [comment]
Just reboot into recovery mode and tick the box next to the OS you want. Thereafter it will boot quicker into that OS unless you press shift to enter recovery mode again.
You only need to reinstall OSes if you want to change them.

**Comment by Haris1977** [comment]
yes but..The 10 second booting screen will just "wont appear anymore" with this way..Right?

And i want it to be able to choose an os..

**Comment by procount** [comment]
OK, so it's not _exactly_ as you want, but I think there are plenty of options:
1) set an autoboot.txt option  to boot directly into one of the installed OSes. This method hides PINN and any other OSes, so the only way to get back into them is to change or delete autoboot.txt. It is the quickest way to boot, but least flexible.
2) Set an OS to sticky boot. This brings up the recovery splash screen to allow you to press the shift key to select another OS temporarily, otherwise PINN will boot your "sticky" Os after a short time. It is a little slower to boot, but more flexible.
3) The default option is to display the boot selection dialog for 10 seconds (adjustable by menuboottimeout) and then boot the LAST OS. It is the slowest boot method, but quite flexible.
4) Setting forcetrigger forces the PINN recovery menu to display until an option is selected, so it provides an indefinite time before boot, but the most flexibility.

It sounds like you want something like 3) but to boot to the stick/favourite option by default instead of the last OS booted. That's not quite available, but I think there is enough choice without it.

**Comment by Haris1977** [comment]
You said in 2 "Set an OS to sticky boot.This brings up the recovery splash screen to allow you to press the shift key to select another OS temporarily, **_otherwise PINN will boot your "sticky" Os after a short time"_**

Does this mean that i have 10 second time to press PROGRAMM UP on my tv to change booting ios? That is exactly what i want..

**Comment by procount** [comment]
Yes.

**Comment by Haris1977** [comment]
Oh nice, thanks, will try it out:)

My thoughts about future updates (in terms of beautification of boot menu)

1) Black background instead of the ugly white one
2) Bigger fonts and bigger square (fonts are very small in big screens) and no cursor in boot menu
3) Give us the possibility to rename (through the shift key) the installed os (eg from openelec_rp1 to OpenELEC Rpi) so as to keep things as clear as possible
4) Programmable cec buttons :)

Just my thoughts:)

**Comment by procount** [comment]
You can now set the background colour in p2.4.5. Not perfect, but it goes some way. no cursor in boot menu can be specified.
OSes will not be renamed because it is part of how the program works.

**Comment by Haris1977** [comment]
Thanks @procount . Any news about bigger fonts/square and programmable cec controls?

**Comment by MartinX3** [comment]
You can also mount the SETTINGS partition, as example, if you insert the micro sd card from the raspberry pi into your computer.
There you can remove the sticky option from the config file. :)
